/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pass_fail.java
 *
 * Created on Nov 11, 2011, 3:07:27 PM
 */
package server;

import java.sql.SQLException;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Pegasus
 */
public class pass_fail extends javax.swing.JFrame {
    dbconnect db;
    String login;
    class verifier extends InputVerifier{
        @Override
    public boolean verify(JComponent pass){
        javax.swing.JPasswordField passw=(javax.swing.JPasswordField)pass;
        if((new String((jPasswordField1.getPassword()))).equals(new String(passw.getPassword()))){
            return true;
        }
        else
            return false;
    }
}
    /** Creates new form pass_fail */
    public pass_fail(String loginid) {
        initComponents();
        login=loginid;
        db=new dbconnect();
        try{
            java.sql.ResultSet rs=db.exeqcommand("select sec_qst from usr_info where login_id=\""+loginid+"\"");
            while(rs.next()){
                int q=new Integer(rs.getString("sec_qst")).intValue();
                pass(q);
            }
        }catch(java.sql.SQLException ex){
            jLabel5.setText("Database error contact admin");
            jLabel5.paintImmediately(jLabel5.getX(), jLabel5.getY(), 50, 15);
        }
    }

    private void pass(int qst){
        String secq[][]={{"what is the name of your best friend from childhood"},
        {"what is your vehicle registration number"},
        {"what was first phone number"},
        {"what was name of your first teacher"},
        {"where you were born"}};
        switch(qst-1){
            case 0:{
                     jLabel5.setText(secq[qst-1][0]);
                     jLabel5.paintImmediately(jLabel5.getX(),jLabel5.getY(),200,10);
                    }
                break;
            case 1:{
                     jLabel5.setText(secq[qst-1][0]);
                     jLabel5.paintImmediately(jLabel5.getX(),jLabel5.getY(),200,10);
                    }
                break;
            case 2:{
                     jLabel5.setText(secq[qst-1][0]);
                     jLabel5.paintImmediately(jLabel5.getX(),jLabel5.getY(),200,10);
                    }
                break;
            case 3:{
                     jLabel5.setText(secq[qst-1][0]);
                     jLabel5.paintImmediately(jLabel5.getX(),jLabel5.getY(),200,10);
                    }
                break;
            case 4:{
                     jLabel5.setText(secq[qst-1][0]);
                     jLabel5.paintImmediately(jLabel5.getX(),jLabel5.getY(),200,10);
                    }
                break;
            default:{
                     jLabel5.setText("Error in getting Question");
                     jLabel5.paintImmediately(jLabel5.getX(),jLabel5.getY(),200,10);
                    }
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Forgot Password");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Password Recovery");

        jLabel2.setText("Secret Question");

        jLabel3.setText("Secret Answer");

        jLabel4.setText("New Password");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jPasswordField1.setEnabled(false);

        jPasswordField2.setEnabled(false);
        jPasswordField2.setInputVerifier(new verifier());
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Re-enter Password");

        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost

        try{
            java.sql.ResultSet rs=db.exeqcommand("select sec_ans from usr_info where login_id=\""+login+"\"");
            while(rs.next()){
                if(jTextField1.getText().equals(rs.getString("sec_ans"))){
                    jPasswordField1.setEnabled(true);
                    jPasswordField2.setEnabled(true);
                    jPasswordField1.requestFocusInWindow();
                }
            }
        }catch(SQLException e){
            jLabel7.setText("Error in databse contact admin");
            jLabel7.paintImmediately(jLabel7.getX(), jLabel7.getY(), 100, 15);
        }
    }//GEN-LAST:event_jTextField1FocusLost

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    if(new String(jPasswordField1.getPassword()).isEmpty())
    {
        jLabel7.setText("Please type password");
        jLabel7.paintImmediately(jLabel7.getX(), jLabel7.getY(), 100, 15);
    }
    try{
        int i=db.updt("update usr_info set password = '"+new String(jPasswordField1.getPassword())+"'"+" where login_id=\""+login+"\"");
        if(i==1){
            JOptionPane.showMessageDialog(rootPane, "Update successful","Doccompanion", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Error in updating databse contact administrator","Doccompanion", JOptionPane.ERROR_MESSAGE);
        }
        setVisible(false);
        dispose();
    }catch(SQLException e){
        jLabel7.setText("Error in databse contact admin");
        jLabel7.paintImmediately(jLabel7.getX(), jLabel7.getY(), 100, 15);
    }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed

        jButton1ActionPerformed(null);
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        jTextField1FocusLost(null);
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
