/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * modusr.java
 *
 * Created on Nov 13, 2011, 12:34:18 PM
 */
package server.setgrp;

import javax.swing.AbstractListModel;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import server.dbconnect;

/**
 *
 * @author Jarvice
 */
public class modusr extends javax.swing.JFrame {
String log;
dbconnect db;
javax.swing.JTable jt;
 class passverifier extends InputVerifier{
        @Override
    public boolean verify(javax.swing.JComponent pass){
        javax.swing.JPasswordField passw=(javax.swing.JPasswordField)pass;
        if((new String((jPasswordField1.getPassword()))).equals(new String(passw.getPassword()))){
            return true;
        }
        else
            return false;
    }
}
class roleslistmodel extends AbstractListModel{
    String[] roles;
    int size;
    
    roleslistmodel(){
        try{
            java.sql.ResultSet rs=db.exeqcommand("select count(role)as counts from (select distinct role from roles) a");
            while(rs.next()){
                size=rs.getInt("counts");
            }
            int count=0;
            roles=new String[size];
            while(count<size){
                roles[count]=new Integer(count).toString();
                count++;
            }
        }catch(java.sql.SQLException e){
            e.printStackTrace();
        }               
    }
        @Override
    public Object getElementAt(int n){
        return roles[n];
    }
        @Override
    public int getSize(){
        return size;
    }
}

    /** Creates new form modusr */
    public modusr(String logid,javax.swing.JTable jtab) {
        
        db=new dbconnect();
        initComponents();
        log=logid;        
        jt=jtab;
        try{
            java.sql.ResultSet rs=db.exeqcommand("select first_name,last_name,roles.login_id as login_id,password,sec_qst,sec_ans,role from usr_info,roles where roles.login_id=usr_info.login_id and roles.login_id=\""+log+"\"");
            while(rs.next()){
                jTextField1.setText(rs.getString("first_name"));
                jTextField2.setText(rs.getString("last_name"));
                jTextField3.setText(rs.getString("login_id"));
                jPasswordField1.setText(rs.getString("password"));
                jPasswordField2.setText(rs.getString("password"));
                jComboBox1.setSelectedIndex(rs.getInt("sec_qst")-1);
                jTextField4.setText(rs.getString("sec_ans"));
                this.setTitle("Modify--"+log);
            }        
        }catch(java.sql.SQLException e){
            System.out.println("Database(SQL) error");
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Modify");

        jLabel5.setText("Re-Enter Password");

        jLabel4.setText("Password");

        jLabel3.setText("Login id");

        jList1.setModel(new roleslistmodel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("Secret Question");

        jLabel7.setText("Secret Answer");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "what is the name of your best friend from childhood", "what is your vehicle registration number", "what was first phone number", "what was name of your first teacher", "where you were born" }));

        jPasswordField2.setInputVerifier(new passverifier());

        jTextField3.setEditable(false);

        jLabel1.setText("First Name");

        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("Last Name");

        jLabel8.setText("Role");

        jLabel9.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, 374, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))))
                    .addGap(5, 5, 5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        try{if(!(jList1.getSelectedIndex()==-1)){
            int i=db.updt("update usr_info set first_name=\""+jTextField1.getText()+"\",last_name=\""+jTextField2.getText()+"\",password=\""+new String(jPasswordField1.getPassword())+"\",sec_qst="+(jComboBox1.getSelectedIndex()+1)+",sec_ans=\""+jTextField4.getText()+"\" where login_id=\""+log+"\"");
            int j=db.updt("update roles set role="+jList1.getSelectedIndex()+" where login_id=+\""+log+"\"");
            if((i==1)&&(j==1)){
            JOptionPane.showMessageDialog(rootPane, "Update successful","Doccompanion", JOptionPane.INFORMATION_MESSAGE);
            jt.updateUI();
            setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Error in updating databse contact administrator","Doccompanion", JOptionPane.ERROR_MESSAGE);
        }}
        else{
            jLabel9.setText("Please select role");
            jLabel9.paintImmediately(jLabel9.getX(), jLabel9.getY(), 50, 15);
        }            
        }catch(java.sql.SQLException e){
            e.printStackTrace();
        }
}//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
