/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reguser.java
 *
 * Created on Nov 13, 2011, 9:18:05 AM
 */
package server.setgrp;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import server.dbconnect;

/**
 *
 * @author Pegasus
 */
public class reguser extends javax.swing.JFrame {
Vector cache;
 dbconnect db;
    class usrtable extends AbstractTableModel{
        
        String[] headers;
        int colCount;
       
        public usrtable(){
            cache=new Vector();
            db=new dbconnect();
            try{
                java.sql.ResultSet rs=db.exeqcommand("select first_name,last_name,roles.login_id as login_id,password,sec_qst,sec_ans,role from usr_info,roles where roles.login_id=usr_info.login_id");
                java.sql.ResultSetMetaData rsmd=rs.getMetaData();
                colCount=rsmd.getColumnCount();
                headers=new String[colCount];
                for(int h=1;h<=colCount;h++){
                    headers[h-1]=rsmd.getColumnLabel(h);
                }
                while(rs.next()){
                    String[] record=new String[rsmd.getColumnCount()];
                    for(int r=0;r<colCount;r++){
                        record[r]=rs.getString(r+1);                        
                    }
                    cache.addElement(record);
                }                
            }catch(java.sql.SQLException e){
                System.out.println("database error");
            }
        }
        @Override
        public String getColumnName(int i){
            return headers[i];
        }
        @Override
        public int getColumnCount(){
            return colCount;
        }
        @Override
        public int getRowCount(){
            return cache.size();
        }
        public Object getValueAt(int row,int col){
            return ((String[]) cache.elementAt(row))[col];
        }
        
    }
    /** Creates new form reguser */
    public reguser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Modify users");

        jTable1.setModel(new usrtable());
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modify");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 
    int row=jTable1.getSelectedRow();
    if(row==-1){
        jLabel1.setText("Please select some row");
        jLabel1.paintImmediately(jLabel1.getX(), jLabel1.getY(), 50, 15);
    }
    else
    {
        String log=((String[]) cache.elementAt(row))[2];
        modusr mu=new modusr(log,jTable1);
        mu.setVisible(true);
        this.setVisible(false);
    }
    
}//GEN-LAST:event_jButton1MouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    int row=jTable1.getSelectedRow();
    if(row==-1){
        jLabel1.setText("Please select some row");
        jLabel1.paintImmediately(jLabel1.getX(), jLabel1.getY(), 50, 15);
    }
    else
    {
        try{
            int i=db.updt("delete from usr_info where login_id=\""+((String[]) cache.elementAt(row))[2]+"\"");
            int j=db.updt("delete from roles where login_id=\""+((String[]) cache.elementAt(row))[2]+"\"");
            if(i==1&&j==1){
                 JOptionPane.showMessageDialog(rootPane, "Update successful","Doccompanion", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Error in updating databse contact administrator","Doccompanion", JOptionPane.ERROR_MESSAGE);
            }
        }catch(java.sql.SQLException e){
            System.out.println("databaase error");
        }
    }
}//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reguser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reguser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reguser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reguser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new reguser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
