/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pass_fail.java
 *
 * Created on Oct 23, 2011, 11:43:25 PM
 */
package client;

import java.io.IOException;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;


/**
 *
 * @author Pegasus
 */
public class pass_fail extends javax.swing.JFrame {
private srvrconnection srvr;
private boolean init;
 class verifier extends InputVerifier{
        @Override
    public boolean verify(JComponent pass){
        javax.swing.JPasswordField passw=(javax.swing.JPasswordField)pass;
        if((new String((jPasswordField1.getPassword()))).equals(new String(passw.getPassword()))){
            return true;
        }
        else
            return false;
    }
}
    /** Creates new form pass_fail */
    public pass_fail(int qst,srvrconnection sr ) {
        initComponents();
        srvr=sr;
        pass(qst);
    }

    private void pass(int qst){
        String secq[][]={{"what is the name of your best friend from childhood"},
        {"what is your vehicle registration number"},
        {"what was first phone number"},
        {"what was name of your first teacher"},
        {"where you were born"}};
        switch(qst-1){
            case 0:{
                     jLabel4.setText(secq[qst-1][0]);
                     jLabel4.paintImmediately(jLabel4.getX(),jLabel4.getY(),200,10);
                    }
                break;
            case 1:{
                     jLabel4.setText(secq[qst-1][0]);
                     jLabel4.paintImmediately(jLabel4.getX(),jLabel4.getY(),200,10);
                    }
                break;
            case 2:{
                     jLabel4.setText(secq[qst-1][0]);
                     jLabel4.paintImmediately(jLabel4.getX(),jLabel4.getY(),200,10);
                    }
                break;
            case 3:{
                     jLabel4.setText(secq[qst-1][0]);
                     jLabel4.paintImmediately(jLabel4.getX(),jLabel4.getY(),200,10);
                    }
                break;
            case 4:{
                     jLabel4.setText(secq[qst-1][0]);
                     jLabel4.paintImmediately(jLabel4.getX(),jLabel4.getY(),200,10);
                    }
                break;
            default:{
                     jLabel4.setText("Error in getting Question");
                     jLabel4.paintImmediately(jLabel4.getX(),jLabel4.getY(),200,10);
                    }
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Password Recovery");

        jLabel3.setText("Security Question");

        jLabel5.setText("Secret Answer");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel6.setText("New Password");

        jPasswordField1.setEnabled(false);

        jLabel7.setText("Re-Enter Password");

        jPasswordField2.setEnabled(false);
        jPasswordField2.setInputVerifier(new verifier());
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Continue");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        try {
            String sec_an=srvr.reply();
            if(sec_an.equals(jTextField1.getText()))
            {
                jPasswordField1.setEnabled(true);
                jPasswordField2.setEnabled(true);
                jPasswordField1.requestFocusInWindow();
            }
            else
            {jLabel2.setText("Wrong answer");
             jLabel2.paintImmediately(jLabel2.getX(), jLabel2.getY(), 100, 15);
             srvr.message("pass update fail");
             setVisible(false);
            }
        } catch (IOException ex) {
            jLabel2.setText("Error in retrieving answer");
            jLabel2.paintImmediately(jLabel2.getX(), jLabel2.getY(), 100, 15);
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try{
             srvr.message("update");
             srvr.message(new String(jPasswordField1.getPassword()));
             if(new Integer(srvr.reply()).intValue()==1)
             {
                 JOptionPane.showMessageDialog(rootPane, "Update successful","Doccompanion", JOptionPane.INFORMATION_MESSAGE);
             }
             else
                 JOptionPane.showMessageDialog(rootPane, "Error in updating databse contact administrator","Doccompanion", JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            dispose();
        }catch(IOException e){
            jLabel2.setText("Error in update");
            jLabel2.paintImmediately(jLabel2.getX(), jLabel2.getY(), 100, 15);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed

        jButton1MouseClicked(null);
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        jTextField1FocusLost(null);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        try{
            srvr.message("pass update fail");
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Critical error please restart client","Doccompanion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
